services:
  airfryer:
    image: airfryer
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airfryer_db
    ports:
      - "8080:8080"
  airfryer_db:
    image: postgres:latest
    container_name: airfryer_db
    environment:
      - POSTGRES_USER=airfryer
      - POSTGRES_PASSWORD=mypassword1234
      - POSTGRES_DB=airfryer
    ports:
      - "5432:5432"
    restart: always