services:
  airfryer:
    image: airfryer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localDevPgPassword1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: